application: chrome-infra-stats
version: 1
runtime: python27
api_version: 1
threadsafe: true

handlers:
- url: /favicon.ico
  static_files: static/favicon.ico
  upload: static/favicon.ico
- url: /mapreduce(/.*)?
  script: mapreduce.main.application
  login: admin
- url: /.*
  script: main.application
